name: Build

on:
  push:

env:
  NINJA_STATUS: '[%f/%t %e %r]'

jobs:
  macOS:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: macos-12
    env:
      TARGET_OS: 'macOS'
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel,RelWithDebInfo]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
   # - name: Setup Xcode
   #   run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Create Build Environment
      shell: bash
      run: brew install ninja nasm
    - name: Build for x86_64 # native build first
      env:
        ARCH: x86_64
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DUSE_LTO=thin -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/x64 # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Build for arm64
      env:
        ARCH: arm64
      shell: bash
      run: |
        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=thin -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/arm64 # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: |
        tar Jcvf devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz


#  macCatalyst:
#    runs-on: macos-12
#    env:
#      TARGET_OS: 'macCatalyst'
#    strategy:
#      fail-fast: false
#      matrix:
#        config: [MinSizeRel]
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        submodules: 'recursive'
#   # - name: Setup Xcode
#   #   run: sudo xcode-select -s /Applications/Xcode_12.4.app
#    - name: Create Build Environment
#      shell: bash
#      run: brew install ninja nasm
#    - name: Build host gen_tab # native build first
#      shell: bash
#      run: |
#        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
#        cmake --build build/host -t gen_tab
#    - name: Build for x86_64
#      env:
#        ARCH: x86_64
#      shell: bash
#      run: |
#        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=thin -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/macCatalyst.cmake -DUSE_BITCODE=0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
#    - name: Build for arm64
#      env:
#        ARCH: arm64
#      shell: bash
#      run: |
#        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=thin -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/macCatalyst.cmake -DUSE_BITCODE=0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
#    - name: Make SDK
#      shell: bash
#      run: |
#        tar Jcvf devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz install
#    - name: Archieve SDK
#      uses: actions/upload-artifact@v3
#      with:
#        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
#        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz


  iOS:
    runs-on: macos-12
    env:
      TARGET_OS: iOS
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel,RelWithDebInfo]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
   # - name: Setup Xcode
   #   run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Create Build Environment
      shell: bash
      run: brew install ninja nasm
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/host -t gen_tab
    - name: Build for arm64
      env:
        ARCH: arm64
      shell: bash
      run: |
        cmake -DHB_IOS=1 -DHB_BUILD_SUBSET=0 -DUSE_LTO=thin -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_IOS_INSTALL_COMBINED=YES -DCMAKE_OSX_SYSROOT=iphoneos -DIOS_DEPLOYMENT_TARGET=8.0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: |
        tar Jcvf devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz


  Windows_VS2022:
    runs-on: windows-2022
    env:
      TARGET_OS: windows-desktop
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel,RelWithDebInfo]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/setup-nasm@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build for win x64
      env:
        ARCH: x64
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DUSE_LTO=1 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - name: Build for win x86
      env:
        ARCH: x86
      run: |
        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=1 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
#    - uses: ilammy/msvc-dev-cmd@v1
#      with:
#        arch: amd64_arm64
#    - name: Build for win arm64 # gas-preprocessor?
#      env:
#        ARCH: arm64
#      run: |
#        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=1 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-vs2022-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z


  UWP_VS2022:
    runs-on: windows-2022
    env:
      TARGET_OS: uwp
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/setup-nasm@v1
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build for host gen_tab
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DUSE_LTO=1 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1  -GNinja  -Bbuild/host -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/host -t gen_tab
    - name: Build for uwp x64
      env:
        ARCH: x64
      run: |
        cmake -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
#    - uses: ilammy/msvc-dev-cmd@v1
#      with:
#        arch: amd64_arm64
#    - name: Build for uwp arm64
#      env:
#        ARCH: arm64
#      run: |
#        cmake -DHB_BUILD_SUBSET=0 -DUSE_LTO=1 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-vs2022-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z


  Android:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: android
      MIN_API: 16
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel] # https://github.com/android/ndk/issues/721
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Create Build Environment
      shell: bash
      run: sudo apt install -y cmake ninja-build nasm
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        cmake --build build/host -t gen_tab
    - name: Build for arm64-v8a
      env:
        ARCH: arm64-v8a
      shell: bash
      run: |
        MIN_API_64=21
        [ $MIN_API -gt 21 ] && MIN_API_64=$MIN_API
        cmake -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DUSE_LTO=thin -DANDROID_LD=lld -DANDROID_ABI=${ARCH} -DANDROID_PLATFORM=android-${MIN_API_64} -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_PIE=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
#    - name: Build for x86_64 # yasm error
#      env:
#        ARCH: x86_64
#      shell: bash
#      run: |
#        cmake -DHB_BUILD_SUBSET=0 -DFT_DISABLE_BROTLI=1 -DFT_DISABLE_PNG=1 -DUSE_LTO=thin -DANDROID_LD=lld -DANDROID_ABI=${ARCH} -DANDROID_PLATFORM=android-${MIN_API} -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_PIE=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z