name: Build

on:
  push:

env:
  NINJA_STATUS: '[%f/%t %e %r]'
  LLVM_VER: ${{ vars.LLVM_VER }}
  VC_LTL_VER: ${{ vars.VC_LTL_VER }}

jobs:
  macOS:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: macos-12
    env:
      TARGET_OS: 'macOS'
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel,RelWithDebInfo]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
   # - name: Setup Xcode
   #   run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Create Build Environment
      shell: bash
      run: |
        brew install ninja nasm
        brew uninstall --ignore-dependencies harfbuzz
    - name: Build for x86_64 # native build first
      env:
        ARCH: x86_64
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/x64 # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Build for arm64
      env:
        ARCH: arm64
      shell: bash
      run: |
        cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/arm64 # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: |
        tar Jcvf devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz


  iOS:
    runs-on: macos-12
    env:
      TARGET_OS: iOS
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
   # - name: Setup Xcode
   #   run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Create Build Environment
      shell: bash
      run: brew install ninja nasm
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/host -t gen_tab
    - name: Build for arm64
      env:
        ARCH: arm64
      shell: bash
      run: |
        cmake -DHB_IOS=1 -DCMAKE_IOS_INSTALL_COMBINED=YES -DCMAKE_SYSTEM_NAME=iOS -DIOS_DEPLOYMENT_TARGET=8.0 -GNinja -DCMAKE_OSX_ARCHITECTURES=${{ env.ARCH }} -Bbuild/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} # no dSYM for lto, dsymutil: no debug symbols in executable (-arch x86_64)
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: |
        tar Jcvf devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.tar.xz


  Windows_VS2022:
    runs-on: windows-2022
    env:
      TARGET_OS: windows-desktop
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel,Debug] # FIXME: build blocked if with debug info
        libass: [1,0]
        exclude:
          - config: MinSizeRel
            libass: 0
          - config: Debug
            libass: 1
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Get libva
      shell: bash
      run: |
        curl -kL -o va.nupkg https://www.nuget.org/api/v2/package/Microsoft.Direct3D.VideoAccelerationCompatibilityPack
        7z x va.nupkg -odep
        mv dep/build/native/x64/include dep
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/setup-nasm@v1
    - name: Use MSVC x64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build for win x64
      env:
        ARCH: x64
      run: |
        clang-cl --version
        cmake -DBUILD_LIBASS=${{ matrix.libass }} -DFRIBIDI_GENTAB=1  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Use MSVC arm64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64
    - name: Build for win arm64
      env:
        ARCH: arm64
      run: |
        cmake -DBUILD_LIBASS=${{ matrix.libass }} -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Use MSVC x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - name: Build for win x86
      env:
        ARCH: x86
      run: |
        cmake  -DBUILD_LIBASS=${{ matrix.libass }} -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-vs2022-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z


  Windows_VS2022_LTL:
    runs-on: windows-2022
    env:
      TARGET_OS: windows-desktop
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: 'Restore dep cache'
      id: dep-cache
      uses: actions/cache@v3
      with:
        path: VC-LTL
        key: dep-${{ vars.VC_LTL_VER }}
    - if: ${{ steps.dep-cache.outputs.cache-hit != 'true' }}
      name: Get VC-LTL
      shell: bash
      run: |
        curl -kL -o ltl.7z https://github.com/Chuyu-Team/VC-LTL5/releases/download/v${VC_LTL_VER}/VC-LTL-${VC_LTL_VER}-Binary.7z
        7z x ltl.7z -oVC-LTL
    - name: Get libva
      shell: bash
      run: |
        curl -kL -o va.nupkg https://www.nuget.org/api/v2/package/Microsoft.Direct3D.VideoAccelerationCompatibilityPack
        7z x va.nupkg -odep
        mv dep/build/native/x64/include dep
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/setup-nasm@v1
    - name: Use NSVC x64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build for win x64
      env:
        ARCH: x64
      run: |
        cmake -DFRIBIDI_GENTAB=1 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_VC_LTL=1 -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Use MSVC x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - name: Build for win x86
      env:
        ARCH: x86
      run: |
        cmake -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_VC_LTL=1 -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_VERSION="6.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022-ltl.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-vs2022-ltl-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022-ltl.7z


  UWP_VS2022:
    runs-on: windows-2022
    env:
      TARGET_OS: uwp
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/setup-nasm@v1
    - name: Use MSVC x64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build for host gen_tab
      run: |
        cmake -DFRIBIDI_GENTAB=1  -GNinja  -Bbuild/host -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/host -t gen_tab
    - name: Build for uwp x64
      env:
        ARCH: x64
      run: |
        cmake  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Use MSVC arm64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64
    - name: Build for uwp arm64
      env:
        ARCH: arm64
      run: |
        cmake  -DCMAKE_SYSTEM_PROCESSOR=${{ env.ARCH }} -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -GNinja  -Bbuild/${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${{ env.ARCH }} -DCMAKE_VERBOSE_MAKEFILE=1 .
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-vs2022-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-vs2022.7z


  Linux_libcxx:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: linux
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: 'Restore sysroot cache'
      id: sysroot-cache
      uses: actions/cache@v3
      with:
        path: ./sysroot
        key: sysroot-${{ env.TARGET_OS }}-${{ secrets.LINUX_SYSROOT_ID }}
    - name: Create Build Environment
      shell: bash
      env:
         SYSROOT_CACHE_HIT: ${{ steps.sysroot-cache.outputs.cache-hit }}
      run: |
        if [[ "$SYSROOT_CACHE_HIT" != "true" ]]; then
          wget https://sourceforge.net/projects/avbuild/files/${TARGET_OS}/${TARGET_OS/r*pi/rpi}-sysroot.tar.xz/download -O sysroot.tar.xz
          tar Jxf sysroot.tar.xz
        fi
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${LLVM_VER} all
        #bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install -y cmake ninja-build nasm libva-dev libvdpau-dev
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        cmake --build build/host -t gen_tab
    - name: Build for x64
      env:
        ARCH: amd64
      shell: bash
      run: |
        cmake -DBUILD_LIBASS=0 -DUSE_LIBCXX=1 -DCMAKE_SYSTEM_PROCESSOR=${ARCH} -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/linux.clang.cmake -DLINUX_SYSROOT=$PWD/sysroot -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Build for arm64
      env:
        ARCH: arm64
      shell: bash
      run: |
        cmake -DBUILD_LIBASS=0 -DUSE_LIBCXX=1 -DCMAKE_SYSTEM_PROCESSOR=${ARCH} -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/linux.clang.cmake -DLINUX_SYSROOT=$PWD/sysroot -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Build for armhf
      env:
        ARCH: armhf
      shell: bash
      run: |
        cmake -DBUILD_LIBASS=0 -DUSE_LIBCXX=1 -DCMAKE_SYSTEM_PROCESSOR=${ARCH} -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/linux.clang.cmake -DLINUX_SYSROOT=$PWD/sysroot -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z

  Linux_gnustl:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: linux
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: 'Restore sysroot cache'
      id: sysroot-cache
      uses: actions/cache@v3
      with:
        path: ./sysroot
        key: sysroot-${{ env.TARGET_OS }}-${{ secrets.LINUX_SYSROOT_ID }}
    - name: Create Build Environment
      shell: bash
      env:
         SYSROOT_CACHE_HIT: ${{ steps.sysroot-cache.outputs.cache-hit }}
      run: |
        if [[ "$SYSROOT_CACHE_HIT" != "true" ]]; then
          wget https://sourceforge.net/projects/avbuild/files/${TARGET_OS}/${TARGET_OS/r*pi/rpi}-sysroot.tar.xz/download -O sysroot.tar.xz
          tar Jxf sysroot.tar.xz
        fi
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${LLVM_VER} all
        #bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install -y cmake ninja-build nasm libva-dev libvdpau-dev
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        cmake --build build/host -t gen_tab
    - name: Build for x64
      env:
        ARCH: amd64
      shell: bash
      run: |
        cmake -DBUILD_LIBASS=0 -DUSE_LIBCXX=0 -DCMAKE_SYSTEM_PROCESSOR=${ARCH} -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/tools/linux.clang.cmake -DLINUX_SYSROOT=$PWD/sysroot -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-gnustl.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-gnustl
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}-gnustl.7z

  Android:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: android
      MIN_API: 16
    strategy:
      fail-fast: false
      matrix:
        config: [MinSizeRel] # https://github.com/android/ndk/issues/721
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Create Build Environment
      shell: bash
      run: sudo apt install -y cmake ninja-build nasm
    - name: Build host gen_tab # native build first
      shell: bash
      run: |
        cmake -DFRIBIDI_GENTAB=1 -Bbuild/host -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        cmake --build build/host -t gen_tab
    - name: Build for arm64-v8a
      env:
        ARCH: arm64-v8a
      shell: bash
      run: |
        MIN_API_64=21
        [ $MIN_API -gt 21 ] && MIN_API_64=$MIN_API
        cmake -DCMAKE_ANDROID_NDK_VERSION=25.1 -DANDROID_LD=lld -DANDROID_ABI=${ARCH} -DANDROID_PLATFORM=android-${MIN_API_64} -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_PIE=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
        cmake --build build/${{ env.ARCH }}
        cmake --install build/${{ env.ARCH }}
#    - name: Build for x86_64 # yasm error
#      env:
#        ARCH: x86_64
#      shell: bash
#      run: |
#        cmake -DCMAKE_ANDROID_NDK_VERSION=25.1 -DANDROID_LD=lld -DANDROID_ABI=${ARCH} -DANDROID_PLATFORM=android-${MIN_API} -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_PIE=ON -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake -GNinja -H$PWD -Bbuild/${ARCH} -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_INSTALL_PREFIX=install/${ARCH} -DCMAKE_VERBOSE_MAKEFILE=1
#        cmake --build build/${{ env.ARCH }}
#        cmake --install build/${{ env.ARCH }}
    - name: Make SDK
      shell: bash
      run: 7z a devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z install
    - name: Archieve SDK
      uses: actions/upload-artifact@v3
      with:
        name: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}
        path: devpkgs-${{ env.TARGET_OS }}-${{ matrix.config }}.7z